- menu_name: "خدمات"

- name: "تواصل معنا"
  url: "/contact/"
  title: "تواصل معنا"

- name: "RSS"
  url: "/feed.xml"
  title: "إشترك في تغذية RSS"

- name: "Atom"
  url: "/atom.xml"
  title: "إشترك في تغذية Atom"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "خريطة الموقع ل Google Webmaster Tools"
